server.port=8082
spring.application.name=mensa_app_backend

spring.datasource.url=jdbc:postgresql://localhost:5432/mensadb
spring.datasource.username=mensa
spring.datasource.password=mensa123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=mensa_backend
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=mensa_backend
mqtt.topic.meals=swt2/meals
mqtt.topic.orders=swt2/orders
