services:
  postgres:
    image: postgres:16
    container_name: postgres-swt2
    environment:
      POSTGRES_DB: mensadb
      POSTGRES_USER: mensa
      POSTGRES_PASSWORD: mensa123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt-swt2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data

volumes:
  pgdata:
  mosquitto_data:
