services:
  postgres:
    image: postgres:16
    container_name: postgres-swt2
    environment:
      POSTGRES_DB: mensadb
      POSTGRES_USER: mensa
      POSTGRES_PASSWORD: mensa123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
